### ISSUE TITLE
Passing tests are treated as failing when used with cucumber framework

### ISSUE THREAD

**Issue by angeloderivco** [christian-bromann/webdriverio-performance-testing#10]
When running the performance service on a suite using wdio cucumber framework, the logs are showing "isTestPassed" as false for all steps.

When I set _dropResultsFromFailedTest_ to true, I get no results even if tests do pass

**Comment by christian-bromann** [comment]
@angeloderivco can you provide a reproducible example?

**Comment by angeloderivco** [comment]
Been a while since this and I don't remember the context nor the setup of what I was trying.
Closing this down for now.
