### ISSUE TITLE
Not able to Run on Sauce or In the Pipeline

### ISSUE THREAD

**Issue by pratimghosh76** [christian-bromann/webdriverio-performance-testing#6]
Hi,
I am able to run in my local properly. But its not working when i want execute it in sauce. Look like Devtools is not able to connect . getting below error (node:33730) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:64533

When I wanted t run it in Docker Pipeline, its failing saying Chrome_Browser path not found. please help me

If some one has implemented it in Sauce or pipeline please share the details. I need it very soon

**Comment by christian-bromann** [comment]
@pratimghosh76 this is unfortunately not yet possible on Sauce.
